const SHOW_ARTICLE = "SHOW_ARTICLE";
const SHOW_USER_HISTORIES = "SHOW_USER_HISTORIES";
const HIDE_USER_HISTORIES = "HIDE_USER_HISTORIES";
const NEXT_USER_POST_HISTORIES = "NEXT_USER_POST_HISTORIES";
const NEXT_USER_TWEET_HISTORIES = "NEXT_USER_TWEET_HISTORIES";
export {
    SHOW_ARTICLE,
    SHOW_USER_HISTORIES,
    HIDE_USER_HISTORIES,
    NEXT_USER_POST_HISTORIES,
    NEXT_USER_TWEET_HISTORIES
};
