const SHOW_ARTICLE = "SHOW_ARTICLE";
const SHOW_USER_HISTORIES = "SHOW_USER_HISTORIES";
const HIDE_USER_HISTORIES = "HIDE_USER_HISTORIES";

export {
    SHOW_ARTICLE,
    SHOW_USER_HISTORIES,
    HIDE_USER_HISTORIES
};
