const SHOW_ARTICLE = "SHOW_ARTICLE";
const SHOW_USER_POST_HISTORIES = "SHOW_USER_POST_HISTORIES";
const SHOW_USER_TWEET_HISTORIES = "SHOW_USER_TWEET_HISTORIES";

export {
    SHOW_ARTICLE,
    SHOW_USER_POST_HISTORIES,
    SHOW_USER_TWEET_HISTORIES
};
